### PR TITLE
fix: Colors of links, code and menu icon

### PR DESCRIPTION
**Pull request by mrluisfer**
Correct the colors of the links, tag code

Also add the svg of the menu icon and dynamic by dark mode

The color of the code tag I choose a random color since they do not have one defined

### CODE REVIEW

**Comment by TeoDev1611** [comment]
Thanks for the contribution you can fix the CLA Assistant license and merge your PR thanks for help to Moldy

**Comment by mrluisfer** [comment]
> Thanks for the contribution you can fix the CLA Assistant license and merge your PR thanks for help to Moldy

ready :D

**Comment by mrluisfer** [comment]
I can't merge the project because I don't think I have the permissions

**Comment by TeoDev1611** [comment]
Thanks for the contribution I make the merge

**Pull request merged**
